### ISSUE TITLE
"Only admins can upload SVG files" message when non-admin user uploads.

### ISSUE THREAD

**Issue by thsdrouot** [Noviat/account_ebics#11] opened 2020-05-20 08:12 UTC
Hi everyone,

We get an error when non-admin user is using the protocol to push CSV on Odoo 12. But it works. 

"Only admins can upload SVG files" 

Does anyone encounter the same problem ?

Thanks.

**Comment by luc-demeyer** [comment] 2020-05-20 08:46
@thsdrouot 
can you give more details (exact scenario of actions taken to reproduce the  problem) ?

**Comment by luc-demeyer** [comment] 2020-06-26 15:45
closing since no feedback.

**Closed as completed by luc-demeyer** 2020-06-26 15:45 UTC
